# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """
$os\
$username\
$nix_shell\
$directory\
$git_branch\
$git_status\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
color_purple = "#cba6f7"
color_red = "#f38ba8"
maroon = "#eba0ac"
color_orange = "#fab387"
color_yellow = "#f9e2af"
color_green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
color_aqua = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
color_insert = "#a6e3a1" # Green
color_normal = '#f5c2e7' # Pink
color_visual = '#f38ba8' # Red
color_replace = '#fab387' # Orange

[palettes.gruvbox_dark]
color_fg0 = '#d4be98'
color_bg1 = '#32302f'
color_bg3 = '#45403d'
color_blue = '#7daea3'
color_aqua = '#89b482'
color_green = '#a9b665'
color_orange = '#e78a4e'
color_purple = '#d3869b'
color_red = '#ea6962'
color_yellow = '#d8a657'
color_insert = '#a9b665'
color_normal = '#a89984'
color_visual = '#ea6962'
color_replace = '#d8a657'

[os]
disabled = true
style = "fg:color_orange"

[os.symbols]
NixOS = " "

[username]
show_always = false
style_user = "bold fg:color_orange"
style_root = "bold fg:color_orange"
format = '[$user ]($style)'

[nix_shell]
disabled = false
style = "bold fg:color_purple"
symbol = ""
format = "[$state $name ]($style)in "

[directory]
style = "bold fg:color_orange"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = ".../"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bold fg:color_aqua"
format = 'on [[$symbol $branch ]($style)]($style)'

[git_status]
style = "bold fg:color_red"
format = '[[\($all_status$ahead_behind\) ]($style)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[󰫶](bold fg:color_insert)'
error_symbol = '[󰫶](bold fg:color_insert)'
vimcmd_symbol = '[󰫻](bold fg:color_normal)'
vimcmd_replace_one_symbol = '[󰫿](bold fg:color_replace)'
vimcmd_replace_symbol = '[󰫿](bold fg:color_replace)'
vimcmd_visual_symbol = '[󰬃](bold fg:color_visual)'
