#! /bin/sh

sxhkd &
# compton --config ~/.config/compton/compton.conf -b & 
picom --config ~/.config/picom/picom.conf -b &
polybar bar -r &
feh --bg-scale ~/Pictures/Wallpapers/pexels-drift-shutterbug-2085998.jpg &
# devmon --no-gui &
# mpd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         5
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle true
bspc config gapless_monocle      true
bspc config focus_follows_pointer false
bspc config focus_by_distance true

bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'
